config: config.yaml
weights: https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-c-seg.pt
cfg: yolov9/models/segment/gelan-c-seg.yaml
data: deep_fashion_dataset/dataset.yaml
hyp:
  lr0: 0.01
  lrf: 0.01
  momentum: 0.937
  weight_decay: 0.0005
  warmup_epochs: 3.0
  warmup_momentum: 0.8
  warmup_bias_lr: 0.1
  box: 7.5
  cls: 0.5
  cls_pw: 1.0
  obj: 0.7
  obj_pw: 1.0
  dfl: 1.5
  iou_t: 0.2
  anchor_t: 5.0
  fl_gamma: 0.0
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  degrees: 0.0
  translate: 0.1
  scale: 0.9
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 1.0
  mixup: 0.15
  copy_paste: 0.3
epochs: 100
batch_size: 8
imgsz: 640
rect: store_true
resume: false
nosave: store_true
noval: store_true
noautoanchor: store_true
noplots: store_true
evolve: null
bucket: ''
cache: null
image_weights: null
device: ''
multi_scale: null
single_cls: null
optimizer: SGD
sync_bn: null
workers: 8
project: runs/train-seg
name: custom-gelan-c-seg.yaml
exist_ok: null
quad: null
cos_lr: null
label_smoothing: 0.0
patience: 5
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
close_mosaic: 0
mask_ratio: 4
no_overlap: null
save_dir: runs/train-seg/custom-gelan-c-seg.yaml
