weights: 'https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-c-seg.pt'
cfg: 'yolov9/models/segment/gelan-c-seg.yaml'
data: 'deep_fashion_dataset/dataset.yaml'
hyp: 'yolov9/data/hyps/hyp.scratch-high.yaml'
epochs: 100
batch-size: 8
imgsz: 640
rect: 'store_true'
resume: False
nosave: 'store_true'
noval: 'store_true'
noautoanchor: 'store_true'
noplots: 'store_true'
evolve: null
bucket: ''
cache: null
image-weights: null
device: ''
multi-scale: null
single-cls: null
optimizer: 'SGD'
sync-bn: null
workers: 8
project: 'runs/train-seg'
name: 'custom-gelan-c-seg.yaml'
exist-ok: null
quad: null
cos-lr: null
label-smoothing: 0.0
patience: 5
freeze: [0]
save-period: -1
seed: 0
local_rank: -1
close-mosaic: 0
mask-ratio: 4
no-overlap: null